// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhqrcrcexqrygtrnzxeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ocXJjcmNleHFyeWd0cm56eGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODQzNTksImV4cCI6MjA3Mjc2MDM1OX0.3Jq9HB-pEBezDoEtah1LGCDlhIEbPmKX6Pfht3pf6yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});